# Generated by Django 5.1.1 on 2024-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
