# Generated by Django 5.1.1 on 2024-09-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='description',
        ),
    ]
