# Generated by Django 5.1.1 on 2024-09-05 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0004_vote_weight_vote_voting_vote_user_id_d468f5_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="restaurant",
            new_name="restaurant_id",
        ),
    ]
