# Generated by Django 5.1.1 on 2024-09-08 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "voting",
            "0011_rename_voting_vote_created_4b1f74_idx_voting_vote_created_7157a3_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameIndex(
            model_name="vote",
            new_name="voting_vote_created_4b1f74_idx",
            old_name="voting_vote_created_7157a3_idx",
        ),
    ]
