# Generated by Django 5.1.1 on 2024-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0012_rename_user_id_vote_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["-created_at"], name="voting_rest_created_81c1e8_idx"
            ),
        ),
    ]
