# Generated by Django 5.1.1 on 2024-09-09 08:29

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("""
            DELETE FROM voting_restaurant
            WHERE id IN (
                SELECT id FROM (
                    SELECT id, ROW_NUMBER() OVER (PARTITION BY name ORDER BY id) AS row_num
                    FROM voting_restaurant
                ) AS t
                WHERE row_num > 1
            );
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0013_restaurant_voting_rest_created_81c1e8_idx"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
