# Generated by Django 5.1.1 on 2024-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0014_remove_duplicate_restaurants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
